name: Publish library to PlatformIO registry

on: push

jobs:
  publish:
    name: Publish library to PlatformIO registry
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Publish tagged commits to registry
      if: startsWith(github.event.ref, 'refs/tags')
      uses: bojit/platformio-publish@main
      with:
        token: ${{ secrets.PLATFORMIO_TOKEN }}
